export const global = {
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 30,
  },
  headline: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  subHeadline: {
    fontSize: 14,
    fontWeight: 'bold',
    padding: 10,
  },
  description: {
    fontSize: 14,
    padding: 10,
  },
  textInput: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 20,
  },
  textInputLarge: {
    height: 300,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 20,
  },
  buttonMenu: {
    width: 250,
    marginBottom: 20,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 30,
    paddingRight: 30,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#000',
  },
  button: {
    marginBottom: 20,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 30,
    paddingRight: 30,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#000',
  },
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  itemFlatList: {
    backgroundColor: '#fff',
    padding: 10,
    fontSize: 14,
    height: 55,
    borderWidth: 1,
    borderColor: '#666',
  },
  itemFlatListAnswered: {
    backgroundColor: '#74DF00',
    padding: 10,
    fontSize: 14,
    height: 55,
    borderWidth: 1,
    borderColor: '#666',
  },
  itemFlatListTitle: {
    fontWeight: 'bold',
    padding: 20,
  },
  itemFlatListDecription: {},
};
