export const global = {
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 30,
  },
  headline: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  subHeadline: {
    fontSize: 14,
    fontWeight: 'bold',
    padding: 10,
  },
  description: {
    fontSize: 14,
    padding: 10,
  },
  descriptionCenter: {
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
  },
  textInput: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 20,
  },
  textInputLarge: {
    height: 300,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 20,
  },
  buttonMenu: {
    width: 250,
    marginBottom: 20,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 30,
    paddingRight: 30,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#000',
  },
  button: {
    marginBottom: 20,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 30,
    paddingRight: 30,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#000',
  },
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  flatListContainer: {
    height: 450,
  },
  itemFlatListContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 10,
    height: 85,
    marginBottom: 1,
  },
  itemFlatList: {
    flexDirection: 'column',
    paddingLeft: 20,
  },
  itemFlatListTitle: {
    fontWeight: 'bold',
    paddingTop: 10,
    fontSize: 14,
    marginTop: -10,
  },
  itemFlatListDecription: {
    fontSize: 14,
  },
  itemFlatListStatus: {
    fontSize: 12,
    color: '#666',
    paddingTop: 5,
    fontStyle: 'italic',
  },
  errorContainer: {
    flexDirection: 'column',
    backgroundColor: '#F6CECE',
    padding: 15,
    flex: 1,
    borderColor: '#B40404',
    borderWidth: 0,
    marginBottom: 10,
  },
  errorContainerHeadline: {
    fontWeight: 'bold',
    color: '#B40404',
  },
  errorContainerText: {
    color: '#B40404',
  },
  loadingIndicatorContainer: {
    flex: 1,
    position: 'absolute',
    left: 0,
    top: 0,
    opacity: 0.9,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerLoginPage: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 30,
    paddingTop: 60,
  },

  // Flex to fill, position absolute,
  // Fixed left/top, and the width set to the window width
};
